name: Keep Render Service Awake

on:
  schedule:
    # Every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render health endpoint
        run: |
          echo "Ping at $(date)"
          STATUS=$(curl -L -s -o /dev/null -w "%{http_code}" --max-time 30 https://airbnb-2xpb.onrender.com || true)
          echo "Health status: $STATUS"
          # Allow 200, 302 (redirect), and 502 (wake-up delay)
          if [ "$STATUS" != "200" ] && [ "$STATUS" != "302" ] && [ "$STATUS" != "502" ]; then
            echo "Health check failed with status $STATUS"
          fi
