name: Keep Render Service Awake

on:
  schedule:
    # Every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render health endpoint
        run: |
          echo "Ping at $(date)"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 https://airbnb-2xpb.onrender.com || true)
          echo "Health status: $STATUS"
          if [ "$STATUS" != "200" ]; then
            echo "Health check failed with status $STATUS" >&2
            exit 1
          fi
