name: Keep Render service awake

on:
  schedule:
    # Every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render health endpoint
        run: |
          # Curl the health endpoint; exit non-zero if not 200
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://airbnb-1-vmnn.onrender.com || true)
          echo "health status: $STATUS"
          if [ "$STATUS" != "200" ]; then
            echo "Health check failed with status $STATUS" >&2
            exit 1
          fi
